[package]
name = "ws-downloader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scraper = "0.14.0"
zip = "0.5"

[[bin]]
name = "scmd-downloader"
path = "src/main.rs"
